version: 0.2

phases:
  install:
    runtime-versions:
       nodejs: 16
  build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install      
      - echo Build started on 'date'
      - npm run build
artifacts:
  files:
    - "build/*"
    - "build/**/*"
  discard-paths: yes